/*
 Jaffar Shorbaji
 September 24th, 2018
 Tells the user their birthday, and spoils Infinity War, and the 2019 joker movie
 */

/**
 *
 * @author jasho9017
 */
public class happyBifday extends javax.swing.JFrame {

    /**
     * Creates new form happyBifday
     */
    public happyBifday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        birthdayInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        theKillingJokePanel = new javax.swing.JPanel();
        killingJoke = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileButton = new javax.swing.JMenu();
        nothingButton = new javax.swing.JMenu();
        JungueefButton = new javax.swing.JMenu();
        joefoefButton = new javax.swing.JMenu();
        helpButton = new javax.swing.JMenu();
        no = new javax.swing.JMenu();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        birthdayLabel.setFont(new java.awt.Font("AbcAmSignLangLetter", 0, 36)); // NOI18N
        birthdayLabel.setForeground(java.awt.Color.magenta);
        birthdayLabel.setText("HAPPY BIRTHDAY");

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        birthdayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayInputActionPerformed(evt);
            }
        });

        nameLabel.setForeground(new java.awt.Color(0, 204, 0));
        nameLabel.setText("Name");

        dateLabel.setForeground(new java.awt.Color(0, 102, 255));
        dateLabel.setText("Date");

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        outputLabel.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N

        killingJoke.setIcon(new javax.swing.ImageIcon("Y:\\Documents\\Bye Bye joker.png")); // NOI18N

        javax.swing.GroupLayout theKillingJokePanelLayout = new javax.swing.GroupLayout(theKillingJokePanel);
        theKillingJokePanel.setLayout(theKillingJokePanelLayout);
        theKillingJokePanelLayout.setHorizontalGroup(
            theKillingJokePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theKillingJokePanelLayout.createSequentialGroup()
                .addComponent(killingJoke)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        theKillingJokePanelLayout.setVerticalGroup(
            theKillingJokePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, theKillingJokePanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(killingJoke)
                .addGap(33, 33, 33))
        );

        fileButton.setText("File");

        nothingButton.setText("Nothing Button");
        fileButton.add(nothingButton);

        menuBar.add(fileButton);

        JungueefButton.setText("Jungueef");
        menuBar.add(JungueefButton);

        joefoefButton.setText("Joefoef");
        menuBar.add(joefoefButton);

        helpButton.setText("Help");

        no.setText("No");
        helpButton.add(no);

        menuBar.add(helpButton);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(dateLabel))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(birthdayInput, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(nameInput)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterButton)
                                .addGap(51, 51, 51)))
                        .addGap(48, 48, 48)
                        .addComponent(theKillingJokePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthdayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(theKillingJokePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        
    }//GEN-LAST:event_nameInputActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        //This line of code is the only important thing, it takes the name and birthday, and gives it a whirl
        String name;
        String date;
        //variable decleration above
        name = nameInput.getText ();
        date = birthdayInput.getText ();
        //takes the users input and makes it cool
        outputLabel.setText (name + "'s birthday is on  " + date + " also everyone dies at the end of infinity war");
    }//GEN-LAST:event_enterButtonActionPerformed

    private void birthdayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayInputActionPerformed

    }//GEN-LAST:event_birthdayInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(happyBifday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(happyBifday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(happyBifday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(happyBifday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new happyBifday().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JungueefButton;
    private javax.swing.JTextField birthdayInput;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JMenu fileButton;
    private javax.swing.JMenu helpButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu joefoefButton;
    private javax.swing.JLabel killingJoke;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JMenu no;
    private javax.swing.JMenu nothingButton;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JPanel theKillingJokePanel;
    // End of variables declaration//GEN-END:variables
}
